### PR TITLE
🐛  Fixes `setValue` when used with HTML

### LINKED ISSUE #12: setValue breaks html return value
Cas effectué sur la branche  [`fix/set-value`](https://github.com/koala-interactive/react-rich-mentions/tree/fix/set-value)

Le setValue retourne 
```html
<em class="emojione" style="font-size: 19px; line-height: 19px;">😉&nbsp;&nbsp;&nbsp;&nbsp;<em class="emojione" style="font-size: 19px; line-height: 19px;">😉&nbsp;<img src=" images="" emojione="" 2620.png" width="19"  height="19"  class="emojione&nbsp;vaM"  =""></img src="></em class="emojione" style="font-size: 19px; line-height: 19px;"></em class="emojione" style="font-size: 19px; line-height: 19px;">
```
au lieu de 
```html
<em class="emojione" style="font-size: 19px; line-height: 19px;">😉</em>    <em class="emojione" style="font-size: 19px; line-height: 19px;">😉</em> <img src="/images/emojione/2620.png" width="19" height="19" class="emojione vaM" />
```

### PR DESCRIPTION
**Pull request by vthibault**
It fixes #12

### CODE REVIEW

File: examples/index.tsx [hunk 1]
```diff
@@ -42,6 +42,11 @@ const Root = () => {
     img.src = require('./unicorn.png');
     ref.current?.insertFragment(':unicorn:', img);
   };
+  const customSetValue = () => {
+    ref.current?.setValue(
+      '<span data-rich-mentions=":smile:" class="emojione" style="font-size: 19px; line-height: 19px;">😉</span>    <span data-rich-mentions=":smile:" class="emojione" style="font-size: 19px; line-height: 19px;">😉</span> <img data-rich-mentions=":smile:" src="/images/emojione/2620.png" width="19" height="19" class="emojione vaM" />'
```
Comment (Muzishell) [inline examples/index.tsx:47]: Maybe it would be clearer to newer contributors if we removed references to our internal classes/styles/images ?

```suggestion
      '<span data-rich-mentions=":smile:">😉</span>    <span data-rich-mentions=":smile:">😉</span> <img data-rich-mentions=":smile:" src="/images/cross"/>'
```

File: src/utils/getConfigsInitialValue.ts [hunk 2]
```diff
@@ -1,14 +1,42 @@
...
-      });
-    }, text);
+    return replaceSpacesWithInsecableSpaces(
+      configs.reduce((acc, config) => {
+        return acc.replace(config.match, $0 => {
+          const span = document.createElement('span');
+          transformFinalFragment(span, $0, config);
+          return span.outerHTML;
+        });
+      }, text)
```
Comment (Muzishell) [inline src/utils/getConfigsInitialValue.ts:39]: It might be easier code to understand if we put this value in a named variable above the return statement.

**Review by Muzishell — APPROVED** [review]
Nice changes !

File: src/utils/getConfigsInitialValue.ts (hunk 2 above)
Comment (vthibault) [reply src/utils/getConfigsInitialValue.ts]: Agree, done on : f19196a

File: examples/index.tsx (hunk 1 above)
Comment (vthibault) [reply examples/index.tsx]: I needed to trick it a little as Parcel generate a dynamic path for the image and Cypress doesn't have a way to get it. f19196a
