### PR TITLE
🐛  Fixes #15 with relative position problem

### LINKED ISSUE #15: Incorrect element position
When using `<Autocomplete fixed={false} />` the library try to calculate the element position but fail if there is a parent with `position:relative` or `position:absolute` style.

It should detect the parent and calculate the position based on the relative parent, else the body if there is none.

### PR DESCRIPTION
**Pull request by vthibault**

### CODE REVIEW

File: src/RichMentionsProvider.tsx [hunk 1]
```diff
@@ -295,10 +295,31 @@ export function RichMentionsProvider<T = object>({
     config: TMentionConfig<T>
   ): void {
     const fixed = ref.current.fixed;
-    const rect = node.getBoundingClientRect();
-    const y = fixed ? 0 : window.pageYOffset;
-    const x = fixed ? 0 : window.pageXOffset;
+    const rect = { top: 0, right: 0, bottom: 0, left: 0 };
```
Comment (Muzishell) [inline src/RichMentionsProvider.tsx:298]: What is the difference of this rect with the previous code ?
Clearer ?

**Review by Muzishell — APPROVED** [review]
Looks legit to me

File: src/RichMentionsProvider.tsx (hunk 1 above)
Comment (vthibault) [reply src/RichMentionsProvider.tsx:298]: The type returned by typescript is readonly so I have to write my own object to update its fields.
